### ISSUE TITLE
Would it be possible to "disable" modules?

### ISSUE THREAD

**Issue by MrAmericanMike** [cyanobacterium/BaseMetals#68] opened 2016-07-06 15:51 UTC
I want to know if would it be possible to disable ores modules that we not using/spawning in the world.

For instance, be able to disable Adamantine, and all the Adamantine related item doesn't generate for that world.

It would be really cool to have this and its a way to have a cleaner modpack.

**Comment by jriwanek** [comment] 2016-07-06 19:39
Duplicate of: https://github.com/cyanobacterium/BaseMetals/issues/55

**Closed as completed by jriwanek** 2016-07-06 19:39 UTC
Labels: duplicate

**Comment by jriwanek** [comment] 2016-07-06 19:40
Btw, you can already edit config/orespawn/basemetals.json and remove the entry for worldgen for a specific ore type, you can also use this to customize generated quantities of various ores.

**Comment by MrAmericanMike** [comment] 2016-07-08 19:30
I already disabled Ores I'm not using. What I mean is that Basemetals still register all the recipes for ores that are not spawning.
For example, I'm not spawning copper, but copper plates, armor, tools and all that stuff is still been registered.

PS: Thanks I see it was a duplicate, hope you can create a feature for this. Thanks once again :D

**Comment by jriwanek** [comment] 2016-07-08 20:27
If you want to remove the recipes, you can always use minetweaker/crafttweaker, I'll have a talk with @cyanobacterium about the ability to disable recipes next time he's around though.

**Comment by MrAmericanMike** [comment] 2016-07-09 12:17
Thanks jriwanek :D Yes that's what I'm doing for this pack. Thanks for your time, and hope Cyano likes the idea, so it can be implemented.
I always like features that can help a pack run faster and also have cleaner JEI (or NEI) results so the player dont get confused with recipes he isn't able to craft ;)
