### ISSUE TITLE
Render Exception

### ISSUE THREAD

**Issue by JoeSchmo2840** [cyanobacterium/BaseMetals#19] opened 2016-02-15 03:27 UTC
Sponge is in this exception but this same exception happens without sponge installed,

https://gist.github.com/JoeSchmo2840/a693920f73f4e5992dd1

**Comment by DrPlantabyte** [comment] 2016-02-15 11:04
Is this with Base Metals v1.7.0 or v1.6.4?

**Comment by crookedzro** [comment] 2016-02-15 11:49
Having the same issue, and its with Base Metals v1.7.0

**Comment by DrPlantabyte** [comment] 2016-02-15 11:57
I'll look into it when I can. Here's some troubleshooting instructions to help narrow down the list of potential bugs.

First, double check that you are using Java 8, just to rule out that as the cause of this error.

Second, is this a server-side only crash or does it crash in single-player too?

Third, if you run a plain Forge server with just Base Metals v1.6.4 (no other mods, no plug-ins), does it give this crash? Then replace v1.6.4 with v1.7.0 and see if that crashes.

**Comment by crookedzro** [comment] 2016-02-15 12:02
Server side only, This only happened when I updated to 1.7.0 of basemetals.
Used latest forge with one mod installed, which would be the latest version of basemetals, and I get a crash.
https://gist.github.com/crookedzro/91a27666ec712452fa52

**Comment by DrPlantabyte** [comment] 2016-02-15 15:00
I figured that might be the case. I must have leaked a reference to the entity renderer somehwere on the server side, even though I only use the rendering code in the client-side proxy function. I'll fix it by tomorrow and release the fix as v1.7.1

**Comment by DrPlantabyte** [comment] 2016-02-16 03:43
It was a super sneaky bug. I didn't mix-up my server and client side code, but I used a lamda in my rendering code and apparently lambdas get parsed by the JVM even when they are never called (unlike normal functions).

Now fixed in version 1.7.1

**Closed as completed by DrPlantabyte** 2016-02-16 03:43 UTC

**Comment by brisingraerowing** [comment] 2016-02-17 04:38
> apparently lambdas get parsed by the JVM even when they are never called

Yet more Java weirdness. All other languages with lambdas (that I know of) DON'T do that.
