### ISSUE TITLE
Mercury oddness: JEI gets confused about the uses for a bucket of Liquid Mercury

### ISSUE THREAD

**Issue by Dizzy611** [cyanobacterium/BaseMetals#40] opened 2016-05-03 05:51 UTC
I had just mined some mercury and powderized it, and was looking at uses for the powder using JEI. I got to the bit where it told me I could make a bucket of liquid mercury, but when I pressed "U" on that, it showed refined and crude oil which could be burned, instead of showing the use for a bucket of liquid mercury.

**Comment by DrPlantabyte** [comment] 2016-05-30 21:46
The problem is that the only use for a Bucket of Mercury in Base Metals is to pour fluid mercury (e.g. suppose you want to have a moat made of mercury like an ancient Chinese Emperor) and that Base Metals uses a universal bucket, so a bucket of oil is the same item as a bucket of mercury, just with different NBT data tags.

Fixing this bug would mean removing the use of universal buckets, and the trouble that would cause is not worth it for the sake of this bug. Won't fix. Sorry.

**Closed as completed by DrPlantabyte** 2016-05-30 21:46 UTC
Labels: bug, wontfix
